"""initial schema

Revision ID: f92b7ef1157e
Revises: 
Create Date: 2026-06-02 18:19:51.748474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92b7ef1157e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_wage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_location_id'), ['location_id'], unique=False)

    op.create_table('pos_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pos_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pos_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_transactions_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pos_transactions_timestamp'), ['timestamp'], unique=False)

    op.create_table('shift_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('shift_name', sa.String(length=255), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_definitions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_definitions_location_id'), ['location_id'], unique=False)

    op.create_table('shift_pl_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_definition_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_labor_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('contribution', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_definition_id'], ['shift_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_pl_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_pl_results_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_pl_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_pl_results_shift_definition_id'), ['shift_definition_id'], unique=False)

    op.create_table('time_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=False),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('wage_override', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_punches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_punches_clock_in'), ['clock_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_punches_clock_out'), ['clock_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_punches_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_punches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_punches_location_id'), ['location_id'], unique=False)

    op.create_table('shift_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_definition_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('time_punch_id', sa.Integer(), nullable=True),
    sa.Column('revenue_allocation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_allocation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shift_definition_id'], ['shift_definitions.id'], ),
    sa.ForeignKeyConstraint(['time_punch_id'], ['time_punches.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_mappings_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_mappings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_mappings_shift_definition_id'), ['shift_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_mappings_time_punch_id'), ['time_punch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_mappings_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_mappings_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_shift_mappings_time_punch_id'))
        batch_op.drop_index(batch_op.f('ix_shift_mappings_shift_definition_id'))
        batch_op.drop_index(batch_op.f('ix_shift_mappings_id'))
        batch_op.drop_index(batch_op.f('ix_shift_mappings_date'))

    op.drop_table('shift_mappings')
    with op.batch_alter_table('time_punches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_punches_location_id'))
        batch_op.drop_index(batch_op.f('ix_time_punches_id'))
        batch_op.drop_index(batch_op.f('ix_time_punches_employee_id'))
        batch_op.drop_index(batch_op.f('ix_time_punches_clock_out'))
        batch_op.drop_index(batch_op.f('ix_time_punches_clock_in'))

    op.drop_table('time_punches')
    with op.batch_alter_table('shift_pl_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_pl_results_shift_definition_id'))
        batch_op.drop_index(batch_op.f('ix_shift_pl_results_id'))
        batch_op.drop_index(batch_op.f('ix_shift_pl_results_date'))

    op.drop_table('shift_pl_results')
    with op.batch_alter_table('shift_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_definitions_location_id'))
        batch_op.drop_index(batch_op.f('ix_shift_definitions_id'))

    op.drop_table('shift_definitions')
    with op.batch_alter_table('pos_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pos_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pos_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_pos_transactions_location_id'))
        batch_op.drop_index(batch_op.f('ix_pos_transactions_id'))

    op.drop_table('pos_transactions')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_location_id'))
        batch_op.drop_index(batch_op.f('ix_employees_id'))

    op.drop_table('employees')
    # ### end Alembic commands ###
